const menu=document.querySelector('.menu'), nav=document.querySelector('nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.style.overflow='';}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':''});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
window.addEventListener('resize',()=>{if(innerWidth>760)closeMenu()});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('.project').forEach(p=>{p.hidden=b.dataset.filter!=='All'&&p.dataset.category!==b.dataset.filter;if(!p.hidden)count++});document.querySelector('#filter-status').textContent=`${count} projects shown`;}));
const caseDialog=document.querySelector('#case-dialog'),lightbox=document.querySelector('#lightbox');
function openImage(src){document.querySelector('#lightbox-image').src=src;lightbox.showModal()}
document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=projects[b.dataset.project];document.querySelector('#case-content').innerHTML=`<div class="case-head"><div class="eyebrow">${p.client} / ${p.cat}</div><h2 id="case-title">${p.title}</h2><p>${p.desc}</p></div><div class="case-steps">${['moment','challenge','insight','idea','making','execution','impact'].map((key,i)=>`<div><h3>0${i+1} — The ${key}</h3><p>${p[key]}</p></div>`).join('')}</div><button class="case-image"><img src="assets/reference-${p.image}.png" alt="${p.desc} — supplied portfolio screenshot">Enlarge original portfolio reference ↗</button>`;document.querySelector('.case-image').onclick=()=>openImage(`assets/reference-${p.image}.png`);caseDialog.showModal();caseDialog.scrollTop=0}));
document.querySelectorAll('[data-lightbox]').forEach(b=>b.onclick=()=>openImage(b.dataset.lightbox));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close()})});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target;observer.unobserve(el);if(reduced)return;const end=Number(el.dataset.count),suffix=el.dataset.suffix||'',start=performance.now();function frame(now){const t=Math.min(1,(now-start)/1300),n=end*(1-Math.pow(1-t,3));el.textContent=(Number.isInteger(end)?Math.round(n):n.toFixed(1))+suffix;if(t<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}),{threshold:.4});document.querySelectorAll('[data-count]').forEach(el=>observer.observe(el));
